spring.application.name=StoryAlive
spring.data.mongodb.auto-index-creation=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
server.tomcat.connection-timeout=24h
server.tomcat.max-swallow-size=1000MB
#! make sure to add the following environment variables before running the application:
jwt.secret=${JWT_SECRET_BASE64}
spring.mongodb.uri=${MONGO_URI}
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=${SUPABASE_BUCKET}
ai.model.url=${AI_MODEL_URL}
gemini.api-key=AQ.Ab8RN6KFwvxUne0cp-rXtXzj9pTEK7dYeGjXXozhzrXbdXYgxw
gemini.baseUrl=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
#! to access swagger   http://localhost:8080/swagger-ui/index.html#/